<?php

/**
 * @file
 * Helper module for token tests.
 */

/**
 * Implements hook_exit().
 */
function token_test_exit() {
  $config = config('token.settings');
  if ($debug = $config->get('page_tokens')) {
    $debug += array('tokens' => array(), 'data' => array(), 'options' => array());
    foreach (array_keys($debug['tokens']) as $token) {
      $debug['values'][$token] = token_replace($token, $debug['data'], $debug['options']);
    }
    $config->set('page_tokens', $debug);
  }
  $config->save();
}

/**
 * Implements hook_date_format_types().
 *
 * @todo Remove when http://drupal.org/node/1173706 is fixed.
 */
function token_test_date_format_types() {
  $info['token_test'] = t('Token test date format');

  // Explicitly set the variable here as well.
  variable_set('date_format_token_test', 'Y');

  return $info;
}
